# Generated by Django 6.0.6 on 2026-06-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('code_invitation', models.CharField(max_length=20, unique=True, verbose_name="Code d'invitation")),
                ('statut_presence', models.CharField(choices=[('en_attente', 'En attente'), ('present', 'Présent'), ('absent', 'Absent')], default='en_attente', max_length=20, verbose_name='Statut de présence')),
                ('choix_boisson', models.CharField(blank=True, choices=[('', '— Choisir —'), ('jus', 'Jus de fruit'), ('vin_rouge', 'Vin rouge'), ('vin_blanc', 'Vin blanc'), ('champagne', 'Champagne'), ('biere', 'Bière'), ('eau', 'Eau')], default='', max_length=20, verbose_name='Choix de boisson')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
            ],
            options={
                'verbose_name': 'Invité',
                'verbose_name_plural': 'Invités',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
